language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t yagiz829/docker-react -f Dockerfile.dev .

script:
  - docker run -e Cl=true yagiz829/docker-react npm run test